POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpY2hpZ3V5IiwiaWQiOiI2ODYzNjY0NWM1ZTBmMjVmN2RlMmU3NjEiLCJpYXQiOjE3NTEzNTM4NTcsImV4cCI6MTc1MTM1NzQ1N30.yR3nIgq8qgoMP9isjI63ReCK7tFf0sxEFn0CYgOHsMw

{
    "title": "Learn NextJS with token middleware",
    "author": "NextJS Org",
    "url": "https://nextjs.org/learn?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=home",
    "likes": 12
}