DELETE http://localhost:3003/api/blogs/68638a0c25e2aa2e7c1599fc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpY2hpZ3V5IiwiaWQiOiI2ODYzNjY0NWM1ZTBmMjVmN2RlMmU3NjEiLCJpYXQiOjE3NTEzNTM4NTcsImV4cCI6MTc1MTM1NzQ1N30.yR3nIgq8qgoMP9isjI63ReCK7tFf0sxEFn0CYgOHsMw